version: '3.8'

services:
  backend:
    build:
      context: ./backend_py
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    env_file:
      - ./backend_py/.env.local
    volumes:
      - ./backend_py:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 3001 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
