version: '3.8'

services:
  backend:
    build:
      context: ./backend_py
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
    env_file:
      - ./backend_py/.env.dev
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
        # Dev: use dev nginx config and point to backend service
        NGINX_CONF: nginx.dev.conf
        VITE_API_URL: http://backend:3001
    ports:
      - "8080:8080"
    depends_on:
      - backend
