version: '3.8'

services:
  backend:
    build:
      context: ./backend_py
      dockerfile: Dockerfile.dev
    container_name: ai-virtual-try-on-backend-py-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=0.0.0.0
    env_file:
      - ./backend_py/.env
    volumes:
      - ./backend_py/app:/app/app
      - ./backend_py/tools:/app/tools
    networks:
      - app-network
    restart: unless-stopped
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 3001

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ai-virtual-try-on-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3001
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

volumes:
  frontend_node_modules:
    driver: local

networks:
  app-network:
    driver: bridge
