version: '3.8'

services:
  backend:
    build:
      context: ./backend_py
      dockerfile: Dockerfile
    container_name: ai-virtual-try-on-backend-py
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
    env_file:
      - ./backend_py/.env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Nginx 프록시 사용: 프런트는 동일 오리진(/api) 호출 → Nginx가 backend로 프록시
        VITE_API_URL: ""
        # Select nginx config: nginx.prod.conf | nginx.dev.conf | nginx.local.conf
        NGINX_CONF: nginx.prod.conf
    container_name: ai-virtual-try-on-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
