name: 🧪 Test Environment CI/CD Pipeline

on:
  push:
    branches: [develop_deploy_pipeline]
  pull_request:
    branches: [develop_deploy_pipeline]
  workflow_dispatch:
    inputs:
      deploy_backend:
        description: 'Deploy Backend to Test'
        type: boolean
        default: true
      deploy_frontend:
        description: 'Deploy Frontend to Test'
        type: boolean
        default: true
      skip_tests:
        description: 'Skip Tests (Emergency Deploy)'
        type: boolean
        default: false

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'
  BACKEND_APP_NAME_TEST: "7ai-team1-backend-test"
  AZURE_RESOURCE_GROUP_HARDCODED: "7ai-final-team1"

jobs:
  # ========== 품질 게이트 ==========
  quality-gate:
    if: github.event.inputs.skip_tests != 'true'
    runs-on: ubuntu-latest
    name: 🔍 Quality Gate

    steps:
    - name: 📦 Checkout Code
      uses: actions/checkout@v4

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: 🐍 Setup Python (No Pip Cache)
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 🔧 Frontend Quality Check
      run: |
        cd frontend
        echo "🔍 Installing frontend dependencies..."
        npm ci --legacy-peer-deps || {
          echo "⚠️ npm ci failed, falling back to npm install"
          rm -f package-lock.json
          npm install --include=dev
        }
        
        echo "🔍 Installing cross-env (Windows/Linux compatibility)..."
        npm install --save-dev cross-env || true
        
        echo "🔍 TypeScript check (lenient for Test environment)..."
        npx tsc --noEmit --skipLibCheck --exclude "**/test/**" --exclude "**/*.test.*" || {
          echo "⚠️ TypeScript warnings exist but continuing for Test environment"
        }
        
        echo "🔍 Build test..."
        rm -rf dist/
        VITE_API_URL=${{ secrets.TEST_BACKEND_URL }} npx vite build --mode test
        
        echo "✅ Frontend quality check passed"

    - name: 🔧 Backend Quality Check
      run: |
        cd backend_py
        echo "🔍 Installing Python dependencies (no cache)..."
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        
        echo "🔍 Python syntax check..."
        python -m py_compile app/main.py
        
        echo "🔍 FastAPI import test..."
        python -c "from app.main import app; print('✅ FastAPI app imports successfully')"
        
        echo "✅ Backend quality check passed"

  # ========== 백엔드 빌드 & 배포 (권한 오류 해결) ==========
  deploy-backend:
    if: github.event.inputs.deploy_backend != 'false'
    needs: quality-gate
    runs-on: ubuntu-latest
    name: 🐍 Deploy Backend to Test
    environment: test
    outputs:
      deployment_status: ${{ steps.deployment.outputs.status }}

    steps:
    - name: 📦 Checkout Code
      uses: actions/checkout@v4

    - name: 🔐 Login to Azure
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    - name: 🔍 Verify Permissions
      run: |
        echo "🔍 Verifying Azure authentication and permissions..."
        az account show --query "{SubscriptionId:id, TenantId:tenantId, User:user.name}"
        
        echo "🔍 Checking Service Principal permissions..."
        az role assignment list --assignee "${{ secrets.AZURE_CLIENT_ID }}" --query "[].{Role:roleDefinitionName, Scope:scope}" -o table || {
          echo "⚠️ Cannot list role assignments - this may indicate insufficient permissions"
        }
        
        echo "🔍 Checking App Service access..."
        az webapp show --name "${{ env.BACKEND_APP_NAME_TEST }}" --resource-group "${{ env.AZURE_RESOURCE_GROUP_HARDCODED }}" --query "{Name:name, State:state}" || {
          echo "❌ Cannot access App Service - check permissions and resource existence"
          exit 1
        }

    - name: 🔐 Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: 🏗️ Build and Push Backend Image
      run: |
        cd backend_py
        echo "🏗️ Building backend Docker image for Test environment..."
        
        docker build \
          --no-cache \
          --platform linux/amd64 \
          -t ${{ env.REGISTRY }}/backend-fastapi-test:latest \
          -t ${{ env.REGISTRY }}/backend-fastapi-test:${{ github.sha }} \
          -f Dockerfile .
        
        echo "📤 Pushing images to ACR..."
        docker push ${{ env.REGISTRY }}/backend-fastapi-test:latest
        docker push ${{ env.REGISTRY }}/backend-fastapi-test:${{ github.sha }}
        
        echo "✅ Backend image build and push completed"

    - name: 🚀 Deploy to Azure App Service (Fixed)
      id: deployment
      run: |
        echo "🚀 Deploying container to App Service..."
        
        # App Service 컨테이너 설정
        az webapp config container set \
          --name "${{ env.BACKEND_APP_NAME_TEST }}" \
          --resource-group "${{ env.AZURE_RESOURCE_GROUP_HARDCODED }}" \
          --docker-custom-image-name "${{ env.REGISTRY }}/backend-fastapi-test:latest" \
          --docker-registry-server-url "https://${{ env.REGISTRY }}" \
          --docker-registry-server-user "${{ secrets.ACR_USERNAME }}" \
          --docker-registry-server-password "${{ secrets.ACR_PASSWORD }}"
        
        echo "✅ Container deployment completed"
        echo "status=success" >> $GITHUB_OUTPUT  # Fixed deprecated set-output

    - name: ⚙️ Configure Environment Variables (Fixed Permissions)
      run: |
        echo "⚙️ Configuring App Service environment variables..."
        
        # 단일 명령어로 모든 환경 변수 설정 (권한 오류 최소화)
        az webapp config appsettings set \
          --name "${{ env.BACKEND_APP_NAME_TEST }}" \
          --resource-group "${{ env.AZURE_RESOURCE_GROUP_HARDCODED }}" \
          --settings \
            PORT=3001 \
            HOST=0.0.0.0 \
            NODE_ENV=test \
            FRONTEND_URL="${{ secrets.TEST_FRONTEND_URL }}" \
            GEMINI_API_KEY="${{ secrets.TEST_GEMINI_API_KEY }}" \
            AZURE_OPENAI_ENDPOINT="${{ secrets.TEST_AZURE_OPENAI_ENDPOINT }}" \
            AZURE_OPENAI_KEY="${{ secrets.TEST_AZURE_OPENAI_KEY }}" \
            AZURE_OPENAI_DEPLOYMENT_ID="${{ secrets.TEST_AZURE_OPENAI_DEPLOYMENT_ID }}" \
            AZURE_OPENAI_API_VERSION="2024-02-15-preview" \
            WEBSITES_ENABLE_APP_SERVICE_STORAGE=false \
            DOCKER_ENABLE_CI=true || {
          
          echo "❌ Failed to set environment variables"
          echo "🔍 Current Service Principal roles:"
          az role assignment list --assignee "${{ secrets.AZURE_CLIENT_ID }}" --query "[].roleDefinitionName" -o table || echo "Cannot list roles"
          exit 1
        }
        
        echo "✅ Environment variables configured successfully"

  # ========== 프론트엔드 빌드 & 배포 ==========
  deploy-frontend:
    if: github.event.inputs.deploy_frontend != 'false'
    needs: quality-gate
    runs-on: ubuntu-latest
    name: 🎨 Deploy Frontend to Test
    environment: test

    steps:
    - name: 📦 Checkout Code
      uses: actions/checkout@v4

    - name: 🟢 Setup Node.js with Cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: 🔧 Install and Build Frontend (Test)
      run: |
        cd frontend
        echo "📦 Installing dependencies with fallback strategy..."
        
        npm ci --legacy-peer-deps || {
          echo "⚠️ npm ci failed, using fallback strategy"
          rm -f package-lock.json
          npm install --include=dev
        }
        
        echo "🔧 Installing cross-env for cross-platform compatibility..."
        npm install --save-dev cross-env || true
        
        echo "🔍 TypeScript validation (lenient for Test)..."
        npx tsc --noEmit --skipLibCheck --exclude "**/test/**" --exclude "**/*.test.*" || {
          echo "⚠️ TypeScript warnings exist but continuing"
        }
        
        echo "🏗️ Building for Test environment..."
        rm -rf dist/
        
        export VITE_API_URL="${{ secrets.TEST_BACKEND_URL }}"
        export VITE_NODE_ENV="test"
        export VITE_DEV_MODE="false"
        
        npx vite build --mode test
        
        echo "📋 Build verification..."
        ls -la dist/
        echo "✅ Frontend build completed successfully"

    - name: 🚀 Deploy to Azure Static Web Apps (Test)
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "frontend/dist"
        skip_app_build: true
        production_branch: "develop_deploy_pipeline"

  # ========== 헬스체크 & 알림 ==========
  health-check:
    needs: [deploy-backend, deploy-frontend]
    if: always() && (needs.deploy-backend.result == 'success' || needs.deploy-frontend.result == 'success')
    runs-on: ubuntu-latest
    name: 🏥 Health Check & Notification

    steps:
    - name: 🏥 Backend Health Check
      if: needs.deploy-backend.result == 'success'
      run: |
        echo "🔍 Waiting for App Service to start..."
        sleep 60  # App Service 시작 대기
        
        echo "🔍 Checking backend health..."
        BACKEND_URL="${{ secrets.TEST_BACKEND_URL }}"
        
        for i in {1..10}; do
          echo "📡 Health check attempt $i/10..."
          
          if curl -f -s --max-time 30 "${BACKEND_URL}/health"; then
            echo "✅ Backend is healthy!"
            echo "BACKEND_HEALTH=success" >> $GITHUB_ENV
            break
          elif [ $i -eq 10 ]; then
            echo "❌ Backend health check failed after 10 attempts"
            echo "BACKEND_HEALTH=failed" >> $GITHUB_ENV
          else
            echo "⏳ Attempt $i failed, retrying in 30s..."
            sleep 30
          fi
        done

    - name: 🏥 Frontend Health Check
      if: needs.deploy-frontend.result == 'success'
      run: |
        echo "🔍 Checking frontend health..."
        FRONTEND_URL="${{ secrets.TEST_FRONTEND_URL }}"
        
        if curl -f -s --max-time 30 "${FRONTEND_URL}"; then
          echo "✅ Frontend is healthy!"
          echo "FRONTEND_HEALTH=success" >> $GITHUB_ENV
        else
          echo "❌ Frontend health check failed"
          echo "FRONTEND_HEALTH=failed" >> $GITHUB_ENV
        fi

    - name: 📊 Test Deployment Summary
      run: |
        echo "## 🧪 Test Environment Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Service | Status | Health | URL |" >> $GITHUB_STEP_SUMMARY
        echo "|---------|--------|---------|-----|" >> $GITHUB_STEP_SUMMARY
        echo "| Backend | ${{ needs.deploy-backend.result }} | ${{ env.BACKEND_HEALTH }} | ${{ secrets.TEST_BACKEND_URL }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Frontend | ${{ needs.deploy-frontend.result }} | ${{ env.FRONTEND_HEALTH }} | ${{ secrets.TEST_FRONTEND_URL }} |" >> $GITHUB_STEP_SUMMARY
        echo "| App Service | ${{ env.BACKEND_APP_NAME_TEST }} | - | - |" >> $GITHUB_STEP_SUMMARY
        echo "| Commit | ${{ github.sha }} | - | - |" >> $GITHUB_STEP_SUMMARY
        echo "| Branch | ${{ github.ref_name }} | - | - |" >> $GITHUB_STEP_SUMMARY
        echo "| Triggered By | ${{ github.actor }} | - | - |" >> $GITHUB_STEP_SUMMARY
        
        echo "🎯 **Test Environment Ready for Validation!**" >> $GITHUB_STEP_SUMMARY

    - name: 📧 Success Notification
      if: success()
      run: |
        echo "🎉 Test deployment successful!"
        echo "Backend: ${{ secrets.TEST_BACKEND_URL }}/health"
        echo "Frontend: ${{ secrets.TEST_FRONTEND_URL }}"
        echo "App Service: ${{ env.BACKEND_APP_NAME_TEST }}"

    - name: 🚨 Failure Notification
      if: failure()
      run: |
        echo "💥 Test deployment failed!"
        echo "Check the logs above for details"
