name: Deploy AI Virtual Try-On to Test Environment

on:
  push:
    branches: [main, develop, develop_deploy_pipeline]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  REGISTRY_USERNAME: ${{ secrets.ACR_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  # 🐳 백엔드 빌드
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend_py
          file: ./backend_py/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/backend-fastapi:latest
            ${{ env.REGISTRY }}/backend-fastapi:${{ github.sha }}

  # ⚛️ 프론트엔드 빌드 (안정화)
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js 20 필수!
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # 안정 버전으로 빌드
      - name: Install and Build Frontend (Stable Versions)
        env:
          NODE_ENV: production
          VITE_API_URL: ${{ secrets.TEST_BACKEND_URL }}
        run: |
          cd frontend
          
          # 완전히 깨끗한 시작
          rm -rf node_modules package-lock.json dist/ .vite
          
          # 안정 버전으로 강제 변경
          cat > package.json << 'EOF'
          {
            "name": "ai-virtual-try-on-frontend",
            "private": true,
            "version": "1.0.0",
            "description": "Frontend React application for AI Virtual Try-On",
            "type": "module",
            "scripts": {
              "dev": "vite",
              "build": "vite build"
            },
            "dependencies": {
              "react": "^18.2.0",
              "react-dom": "^18.2.0",
              "html2canvas": "^1.4.1"
            },
            "devDependencies": {
              "@testing-library/jest-dom": "^6.4.5",
              "@testing-library/react": "^15.0.0",
              "@types/react": "^18.2.43",
              "@types/react-dom": "^18.2.17",
              "@typescript-eslint/eslint-plugin": "^6.14.0",
              "@typescript-eslint/parser": "^6.14.0",
              "@vitejs/plugin-react": "^4.2.1",
              "autoprefixer": "^10.4.16",
              "eslint": "^8.55.0",
              "eslint-plugin-react-hooks": "^4.6.0",
              "eslint-plugin-react-refresh": "^0.4.5",
              "jsdom": "^23.0.1",
              "postcss": "^8.4.32",
              "tailwindcss": "^3.3.6",
              "terser": "^5.43.1",
              "typescript": "^5.2.2",
              "vite": "^5.4.8",
              "vitest": "^1.0.4"
            }
          }
          EOF
          
          # 안정적인 설치 및 빌드
          npm install --legacy-peer-deps
          npm run build
          
          # 빌드 확인
          ls -la dist/
          echo "✅ 프론트엔드 빌드 성공"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          build-args: |
            NGINX_CONF=nginx.prod.conf
            VITE_API_URL=${{ secrets.TEST_BACKEND_URL }}
          tags: |
            ${{ env.REGISTRY }}/frontend-react:latest
            ${{ env.REGISTRY }}/frontend-react:${{ github.sha }}

      - name: Deploy to Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          output_location: "dist"
          skip_app_build: true

  # 🚀 백엔드 배포 (개별 시크릿 사용)
  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure (Service Principal)
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.BACKEND_WEBAPP_NAME }}
          images: ${{ env.REGISTRY }}/backend-fastapi:${{ github.sha }}

  # 📊 결과 알림
  notify:
    needs: [build-backend, build-frontend, deploy-backend]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Summary
        run: |
          echo "🎉 AI Virtual Try-On 배포 결과"
          echo "백엔드: ${{ needs.build-backend.result }}"
          echo "프론트엔드: ${{ needs.build-frontend.result }}"
          echo "배포: ${{ needs.deploy-backend.result }}"